image: cirrusci/flutter:stable

stages:
  - build
  - test

before_script:
  - flutter pub get
  - flutter clean

build:
  stage: build

  script:
    - flutter build aot

  tags:
    - linux
    - docker

  only:
    - merge_requests

unit_test:
  stage: test

  script:
    - flutter test test/*

  tags:
    - linux
    - docker

