image: cirrusci/flutter:stable

stages:
  - test_code_quality
  - test
  - test_coverage

before_script:
  - flutter pub get
  - flutter clean
  - flutter --version    
  - pub global activate dart_code_metrics
  - export PATH="$PATH":"$HOME/.pub-cache/bin"


unit_test:
  stage: test

  script:
    - flutter test test/*

  tags:
    - linux
    - docker

code_quality:
  stage: test_code_quality
  script:
    - metrics lib -r codeclimate  > gl-code-quality-report.json

  tags:
    - linux
    - docker
    
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

test_coverage:
  stage: test_coverage
  
  script:
    - flutter test --coverage ./lib 
    - lcov -r coverage/lcov.info '*/__test*__/*' -o coverage/lcov_cleaned.info
    - genhtml coverage/lcov_cleaned.info --output=coverage
  artifacts:
    paths:
      - coverage
  tags:
    - linux
    - docker

