image: cirrusci/flutter:stable

stages:
  - test_code_quality
  - test
  - test_coverage

before_script:
  - flutter pub get
  - flutter clean
  - flutter --version    
  - flutter test --machine > report.json
  - pub global activate dart_code_metrics
  - export PATH="$PATH":"$HOME/.pub-cache/bin"

code_quality:
  stage: test_code_quality
  script:
    - metrics lib -r codeclimate  > gl-code-quality-report.json

  tags:
    - linux
    - docker
    
  artifacts:
    reports:
      codequality: gl-code-quality-report.json



unit_test:
  stage: test
  pub_cache:
    folder: ~/.pub-cache
  test_script: flutter test -machine > report.json
  always:
    report_artifacts:
      path: report.json
      format: flutter

test_coverage:
  stage: test_coverage
  
  script:
    - flutter test --coverage ./lib 
    - lcov -r coverage/lcov.info '*/__test*__/*' -o coverage/lcov_cleaned.info
    - genhtml coverage/lcov_cleaned.info --output=coverage
  artifacts:
    paths:
      - coverage
  tags:
    - linux
    - docker

