image: cirrusci/flutter:stable

  
before_script:
  - flutter pub get
  - flutter clean
  - flutter --version    
  - flutter pub pub global activate junitreport
  - export PATH="$PATH":"$HOME/.pub-cache/bin"


unit_test:
  script:
    - flutter test --machine > test_report.json
    # replace all "\u001b" in jsonreport cause its not valid for xml:
    - sed -i 's/\\u001b//g' test_report.json 
    - flutter pub global run junitreport:tojunit --input test_report.json --output test_results_junit.xml

  tags:
    - linux
    - docker

  artifacts:
    reports:
      junit: test_results_junit.xml
    paths:
      - test_results_junit.xml

test_coverage:
  script:
    - flutter test --coverage ./lib 
    - lcov -r coverage/lcov.info '*/__test*__/*' -o coverage/lcov_cleaned.info
    - genhtml coverage/lcov_cleaned.info --output=coverage
  artifacts:
    paths:
      - coverage
  tags:
    - linux
    - docker


