image: cirrusci/flutter:stable

stages:
  - test
  - test_coverage

before_script:
  - flutter pub get
  - flutter clean
  - flutter --version
  - flutter pub global activate junitreport
  - export PATH="$PATH":"$HOME/.pub-cache/bin"

unit_test:
  stage: test

  script:
    - flutter test test/* | tojunit -o report.xml

  tags:
    - linux
    - docker

  artifacts:
    when: always
    reports:
      junit:
        - report.xml

test_coverage:
  stage: test_coverage
  
  script:
    - flutter test --coverage ./lib 
    - lcov -r coverage/lcov.info '*/__test*__/*' -o coverage/lcov_cleaned.info
    - genhtml coverage/lcov_cleaned.info --output=coverage
  artifacts:
    paths:
      - coverage
  tags:
    - linux
    - docker

