image: cirrusci/flutter:stable

stages:
  - test

before_script:
  - flutter pub get
  - flutter clean

unit_test:
  stage: test

  script:
    - flutter test test/*

  tags:
    - linux
    - shell

