name: Build
on:
  schedule:
    # this executes at 03:00 every night
    # see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '0 3 * * *'

env:
  FLUTTER_VERSION: '2.8.1'

jobs:
  android:
    name: Build Android APK and app bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
      - name: Run build
        run: |
          flutter config --no-analytics
          flutter build apk
          flutter build appbundle

  ios:
    name: Build for iOS
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
      - name: Run build
        run: |
          flutter config --no-analytics
          flutter build ios --release --no-codesign

  web:
    name: Build for web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
      - name: Run build
        run: |
          flutter config --no-analytics
          flutter build web

  windows:
    name: Build for windows
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
      - name: Run build
        run: |
          flutter config --no-analytics
          flutter config --enable-windows-desktop
          flutter build windows

  linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - name: Run build
        run: |
          flutter config --no-analytics
          flutter config --enable-linux-desktop
          flutter build linux

  macos:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - name: Run build
        run: |
          flutter config --no-analytics
          flutter config --enable-macos-desktop
          flutter build macos
