name: Build
on:
  schedule:
    # this executes at 03:00 every night
    # see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '0 3 * * *'

jobs:
  windows:
    name: Build for windows
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Run build
        run: |
          flutter config --no-analytics
          flutter config --enable-windows-desktop
          flutter build windows

  linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - name: Run build
        run: |
          flutter config --no-analytics
          flutter config --enable-linux-desktop
          flutter build linux

  macos:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Run build
        run: |
          flutter config --no-analytics
          flutter config --enable-macos-desktop
          flutter build macos
